"""
This file holds all the constants necessary to recreate Shotgun data locally.
"""

API_KEY = "2b3f3b6e442242c067501a9e17503bac1d27b6ea244a4e4b5987e26d5f6520e2"
API_NAME = "Samuel - API"
SHOTGUN_URL = "https://objeus.shotgunstudio.com"

ENTITY_PATH = "data/entities/"

"""
ENTITY_MAP = {
    "Spell":"CustomEntity01",
    "Story":"CustomEntity02",
    "Aspect":"CustomEntity03",
    "Programming Ticket":"CustomEntity04",
    "Character":"CustomEntity06",
    "Persona":"CustomEntity07",
    "JSON Script":"CustomEntity08",
    "Developer Documentation":"CustomEntity09",
    "Weapon":"CustomEntity10",
    "Gear":"CustomEntity11",
    "Item":"CustomEntity12",
    "Music":"CustomEntity13",
    "Story Day":"CustomEntity15",
    "Voice Line":"CustomEntity17",
    "Circle of Hell":"CustomEntity18"
}
"""
ENTITY_MAP = {
    "Action Menu Item": "ActionMenuItem",
    "Asset": "Asset",
    "Department": "Department",
    "Revision Ticket Connection": "RevisionTicketConnection",
    "Revision": "Revision",
    "Cut Version Connection": "CutVersionConnection",
    "Published File Dependency": "PublishedFileDependency",
    "Step": "Step",
    "Custom Entity16 Sg Events Connection": "CustomEntity16_sg_events_Connection",
    "Icon": "Icon",
    "Task": "Task",
    "Script": "ApiUser",
    "Asset Level Connection": "AssetLevelConnection",
    "Project": "Project",
    "Cut Item": "CutItem",
    "Local Storage": "LocalStorage",
    "Launch Scene Connection": "LaunchSceneConnection",
    "Release Ticket Connection": "ReleaseTicketConnection",
    "Story": "CustomEntity02",
    "Aspects": "CustomEntity03",
    "Spell": "CustomEntity01",
    "Character": "CustomEntity06",
    "Persona": "CustomEntity07",
    "Programming Tickets": "CustomEntity04",
    "JSON Scripts": "CustomEntity08",
    "Developer Documentation": "CustomEntity09",
    "Asset Asset Connection": "AssetAssetConnection",
    "Tag": "Tag",
    "Event Log Entry": "EventLogEntry",
    "Asset Shoot Day Connection": "AssetShootDayConnection",
    "Launch Shot Connection": "LaunchShotConnection",
    "Banner User Connection": "BannerUserConnection",
    "Shoot Day Scene Connection": "ShootDaySceneConnection",
    "Version": "Version",
    "Reply": "Reply",
    "App Welcome User Connection": "AppWelcomeUserConnection",
    "Gear": "CustomEntity11",
    "Weapons": "CustomEntity10",
    "Music": "CustomEntity13",
    "Items": "CustomEntity12",
    "Story Days": "CustomEntity15",
    "Voice Lines": "CustomEntity17",
    "Circle of Hell": "CustomEntity18",
    "Playlist Share": "PlaylistShare",
    "Custom Entity06 Sg Voice Lines Connection": "CustomEntity06_sg_voice_lines_Connection",
    "Ticket Ticket Connection": "TicketTicketConnection",
    "Level": "CustomEntity28",
    "Asset Element Connection": "AssetElementConnection",
    "Cut": "Cut",
    "Group": "Group",
    "Note": "Note",
    "Task Dependency": "TaskDependency",
    "Page Hit": "PageHit",
    "File": "Attachment",
    "Status": "Status",
    "Group User Connection": "GroupUserConnection",
    "Physical Asset Mocap Take Connection": "PhysicalAssetMocapTakeConnection",
    "Mocap Take Range Shot Connection": "MocapTakeRangeShotConnection",
    "Task Sg Sub Tasks Connection": "Task_sg_sub_tasks_Connection",
    "Asset Blendshape Connection": "AssetBlendshapeConnection",
    "Pipeline Configuration User Connection": "PipelineConfigurationUserConnection",
    "Published File": "PublishedFile",
    "Project User Connection": "ProjectUserConnection",
    "Shot Shot Connection": "ShotShotConnection",
    "Published File Type": "PublishedFileType",
    "Task Template": "TaskTemplate",
    "Performer Shoot Day Connection": "PerformerShootDayConnection",
    "Pipeline Configuration": "PipelineConfiguration",
    "Person": "HumanUser",
    "Software": "Software",
    "Filesystem Location": "FilesystemLocation",
    "Element Shot Connection": "ElementShotConnection",
    "Asset Episode Connection": "AssetEpisodeConnection",
    "Custom Entity09 Sg Documentation For Connection": "CustomEntity09_sg_documentation_for_Connection",
    "Asset Scene Connection": "AssetSceneConnection",
    "Asset Mocap Take Connection": "AssetMocapTakeConnection",
    "Camera Mocap Take Connection": "CameraMocapTakeConnection",
    "Booking": "Booking",
    "Playlist Version Connection": "PlaylistVersionConnection",
    "Phase": "Phase",
    "Asset Shot Connection": "AssetShotConnection",
    "Client User": "ClientUser",
    "Page Setting": "PageSetting",
    "Custom Entity28 Sg Assets Connection": "CustomEntity28_sg_assets_Connection",
    "Performer Routine Connection": "PerformerRoutineConnection",
    "Api User Project Connection": "ApiUserProjectConnection",
    "Ticket Sg Related Assets Connection": "Ticket_sg_related_assets_Connection",
    "Permission Rule Set": "PermissionRuleSet",
    "Project Task Template Connection": "ProjectTaskTemplateConnection",
    "Asset Sequence Connection": "AssetSequenceConnection",
    "Page": "Page",
    "Performer Mocap Take Connection": "PerformerMocapTakeConnection",
    "Revision Revision Connection": "RevisionRevisionConnection"
}
