"""
This file holds all the constants necessary to recreate Shotgun data locally.
"""

API_KEY = "pjyvy5znakgltt*pmnnhNkaey"
API_NAME = "AIGun"
SHOTGUN_URL = "https://objeus.shotgunstudio.com"

ENTITY_PATH = "data/entities/"

"""
ENTITY_MAP = {
    "Spell":"CustomEntity01",
    "Story":"CustomEntity02",
    "Aspect":"CustomEntity03",
    "Programming Ticket":"CustomEntity04",
    "Character":"CustomEntity06",
    "Persona":"CustomEntity07",
    "JSON Script":"CustomEntity08",
    "Developer Documentation":"CustomEntity09",
    "Weapon":"CustomEntity10",
    "Gear":"CustomEntity11",
    "Item":"CustomEntity12",
    "Music":"CustomEntity13",
    "Story Day":"CustomEntity15",
    "Voice Line":"CustomEntity17",
    "Circle of Hell":"CustomEntity18"
}
"""
ENTITY_MAP = {
    "Action Menu Item": "ActionMenuItem",
    "Asset": "Asset",
    "Department": "Department",
    "Revision Ticket Connection": "RevisionTicketConnection",
    "Revision": "Revision",
    "Cut Version Connection": "CutVersionConnection",
    "Published File Dependency": "PublishedFileDependency",
    "Step": "Step",
    "Custom Entity16 Sg Events Connection": "CustomEntity16_sg_events_Connection",
    "Icon": "Icon",
    "Task": "Task",
    "Script": "ApiUser",
    "Asset Level Connection": "AssetLevelConnection",
    "Project": "Project",
    "Cut Item": "CutItem",
    "Local Storage": "LocalStorage",
    "Launch Scene Connection": "LaunchSceneConnection",
    "Release Ticket Connection": "ReleaseTicketConnection",
    "Story": "CustomEntity02",
    "Aspects": "CustomEntity03",
    "Spell": "CustomEntity01",
    "Character": "CustomEntity06",
    "Persona": "CustomEntity07",
    "Programming Tickets": "CustomEntity04",
    "JSON Scripts": "CustomEntity08",
    "Developer Documentation": "CustomEntity09",
    "Asset Asset Connection": "AssetAssetConnection",
    "Tag": "Tag",
    "Event Log Entry": "EventLogEntry",
    "Asset Shoot Day Connection": "AssetShootDayConnection",
    "Launch Shot Connection": "LaunchShotConnection",
    "Banner User Connection": "BannerUserConnection",
    "Shoot Day Scene Connection": "ShootDaySceneConnection",
    "Version": "Version",
    "Reply": "Reply",
    "App Welcome User Connection": "AppWelcomeUserConnection",
    "Gear": "CustomEntity11",
    "Weapons": "CustomEntity10",
    "Music": "CustomEntity13",
    "Items": "CustomEntity12",
    "Story Days": "CustomEntity15",
    "Voice Lines": "CustomEntity17",
    "Circle of Hell": "CustomEntity18",
    "Playlist Share": "PlaylistShare",
    "Custom Entity06 Sg Voice Lines Connection": "CustomEntity06_sg_voice_lines_Connection",
    "Ticket Ticket Connection": "TicketTicketConnection",
    "Level": "CustomEntity28",
    "Asset Element Connection": "AssetElementConnection",
    "Cut": "Cut",
    "Group": "Group",
    "Note": "Note",
    "Task Dependency": "TaskDependency",
    "Page Hit": "PageHit",
    "File": "Attachment",
    "Status": "Status",
    "Group User Connection": "GroupUserConnection",
    "Physical Asset Mocap Take Connection": "PhysicalAssetMocapTakeConnection",
    "Mocap Take Range Shot Connection": "MocapTakeRangeShotConnection",
    "Task Sg Sub Tasks Connection": "Task_sg_sub_tasks_Connection",
    "Asset Blendshape Connection": "AssetBlendshapeConnection",
    "Pipeline Configuration User Connection": "PipelineConfigurationUserConnection",
    "Published File": "PublishedFile",
    "Project User Connection": "ProjectUserConnection",
    "Shot Shot Connection": "ShotShotConnection",
    "Published File Type": "PublishedFileType",
    "Task Template": "TaskTemplate",
    "Performer Shoot Day Connection": "PerformerShootDayConnection",
    "Pipeline Configuration": "PipelineConfiguration",
    "Person": "HumanUser",
    "Software": "Software",
    "Filesystem Location": "FilesystemLocation",
    "Element Shot Connection": "ElementShotConnection",
    "Asset Episode Connection": "AssetEpisodeConnection",
    "Custom Entity09 Sg Documentation For Connection": "CustomEntity09_sg_documentation_for_Connection",
    "Asset Scene Connection": "AssetSceneConnection",
    "Asset Mocap Take Connection": "AssetMocapTakeConnection",
    "Camera Mocap Take Connection": "CameraMocapTakeConnection",
    "Booking": "Booking",
    "Playlist Version Connection": "PlaylistVersionConnection",
    "Phase": "Phase",
    "Asset Shot Connection": "AssetShotConnection",
    "Client User": "ClientUser",
    "Page Setting": "PageSetting",
    "Custom Entity28 Sg Assets Connection": "CustomEntity28_sg_assets_Connection",
    "Performer Routine Connection": "PerformerRoutineConnection",
    "Api User Project Connection": "ApiUserProjectConnection",
    "Ticket Sg Related Assets Connection": "Ticket_sg_related_assets_Connection",
    "Permission Rule Set": "PermissionRuleSet",
    "Project Task Template Connection": "ProjectTaskTemplateConnection",
    "Asset Sequence Connection": "AssetSequenceConnection",
    "Page": "Page",
    "Performer Mocap Take Connection": "PerformerMocapTakeConnection",
    "Revision Revision Connection": "RevisionRevisionConnection"
}


ENTITY_REVERSE_MAP = {
    'ActionMenuItem': 'Action Menu Item',
    'ApiUser': 'Script',
    'ApiUserProjectConnection': 'Api User Project Connection',
    'AppWelcomeUserConnection': 'App Welcome User Connection',
    'Asset': 'Asset',
    'AssetAssetConnection': 'Asset Asset Connection',
    'AssetBlendshapeConnection': 'Asset Blendshape Connection',
    'AssetElementConnection': 'Asset Element Connection',
    'AssetEpisodeConnection': 'Asset Episode Connection',
    'AssetLevelConnection': 'Asset Level Connection',
    'AssetMocapTakeConnection': 'Asset Mocap Take Connection',
    'AssetSceneConnection': 'Asset Scene Connection',
    'AssetSequenceConnection': 'Asset Sequence Connection',
    'AssetShootDayConnection': 'Asset Shoot Day Connection',
    'AssetShotConnection': 'Asset Shot Connection',
    'Attachment': 'File',
    'BannerUserConnection': 'Banner User Connection',
    'Booking': 'Booking',
    'CameraMocapTakeConnection': 'Camera Mocap Take Connection',
    'ClientUser': 'Client User',
    'CustomEntity01': 'Spell',
    'CustomEntity02': 'Story',
    'CustomEntity03': 'Aspects',
    'CustomEntity04': 'Programming Tickets',
    'CustomEntity06': 'Character',
    'CustomEntity06_sg_voice_lines_Connection': 'Custom Entity06 Sg Voice Lines Connection',
    'CustomEntity07': 'Persona',
    'CustomEntity08': 'JSON Scripts',
    'CustomEntity09': 'Developer Documentation',
    'CustomEntity09_sg_documentation_for_Connection': 'Custom Entity09 Sg Documentation For Connection',
    'CustomEntity10': 'Weapons',
    'CustomEntity11': 'Gear',
    'CustomEntity12': 'Items',
    'CustomEntity13': 'Music',
    'CustomEntity15': 'Story Days',
    'CustomEntity16_sg_events_Connection': 'Custom Entity16 Sg Events Connection',
    'CustomEntity17': 'Voice Lines',
    'CustomEntity18': 'Circle of Hell',
    'CustomEntity28': 'Level',
    'CustomEntity28_sg_assets_Connection': 'Custom Entity28 Sg Assets Connection',
    'Cut': 'Cut',
    'CutItem': 'Cut Item',
    'CutVersionConnection': 'Cut Version Connection',
    'Department': 'Department',
    'ElementShotConnection': 'Element Shot Connection',
    'EventLogEntry': 'Event Log Entry',
    'FilesystemLocation': 'Filesystem Location',
    'Group': 'Group',
    'GroupUserConnection': 'Group User Connection',
    'HumanUser': 'Person',
    'Icon': 'Icon',
    'LaunchSceneConnection': 'Launch Scene Connection',
    'LaunchShotConnection': 'Launch Shot Connection',
    'LocalStorage': 'Local Storage',
    'MocapTakeRangeShotConnection': 'Mocap Take Range Shot Connection',
    'Note': 'Note',
    'Page': 'Page',
    'PageHit': 'Page Hit',
    'PageSetting': 'Page Setting',
    'PerformerMocapTakeConnection': 'Performer Mocap Take Connection',
    'PerformerRoutineConnection': 'Performer Routine Connection',
    'PerformerShootDayConnection': 'Performer Shoot Day Connection',
    'PermissionRuleSet': 'Permission Rule Set',
    'Phase': 'Phase',
    'PhysicalAssetMocapTakeConnection': 'Physical Asset Mocap Take Connection',
    'PipelineConfiguration': 'Pipeline Configuration',
    'PipelineConfigurationUserConnection': 'Pipeline Configuration User Connection',
    'PlaylistShare': 'Playlist Share',
    'PlaylistVersionConnection': 'Playlist Version Connection',
    'Project': 'Project',
    'ProjectTaskTemplateConnection': 'Project Task Template Connection',
    'ProjectUserConnection': 'Project User Connection',
    'PublishedFile': 'Published File',
    'PublishedFileDependency': 'Published File Dependency',
    'PublishedFileType': 'Published File Type',
    'ReleaseTicketConnection': 'Release Ticket Connection',
    'Reply': 'Reply',
    'Revision': 'Revision',
    'RevisionRevisionConnection': 'Revision Revision Connection',
    'RevisionTicketConnection': 'Revision Ticket Connection',
    'ShootDaySceneConnection': 'Shoot Day Scene Connection',
    'ShotShotConnection': 'Shot Shot Connection',
    'Software': 'Software',
    'Status': 'Status',
    'Step': 'Step',
    'Tag': 'Tag',
    'Task': 'Task',
    'TaskDependency': 'Task Dependency',
    'TaskTemplate': 'Task Template',
    'Task_sg_sub_tasks_Connection': 'Task Sg Sub Tasks Connection',
    'TicketTicketConnection': 'Ticket Ticket Connection',
    'Ticket_sg_related_assets_Connection': 'Ticket Sg Related Assets Connection',
    'Version': 'Version'
}
